import './globals.css'
import { ContextProvider } from './context'

export const metadata = {
  title: 'Chaty',
  description: 'Generated by Daiana Arena',
}

//List of pages in this project
const Links = [
  {
    label: "Home",
    route: "/"
  },
  {
    label: "Sign in",
    route: "/pages/signin"
  },
  {
    label: "Chat",
    route: "/pages/chats"
  }

]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <ContextProvider>
        {children}
        </ContextProvider>
      </body>
      
    </html>
  )
}
